name: rapid cli .NET Core release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Install dependencies
        run: dotnet restore ./tools/rsdl/dotnet/rapid/rapid.csproj

      - name: Create NuGet Package
        run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/oasis-open/odata-rapid/releases/tag/${{ github.event.release.tag_name }}"
        working-directory: ./src

      - name: Archive NuGet Package
        uses: actions/upload-artifact@v1
        with:
          name: Code.Library
          path: ./tools/rsdl/dotnet/rapid/nupkg/rapid.${{ github.event.release.tag_name }}.nupkg

      - name: Publish Nuget Package
        run: dotnet nuget push ./tools/rsdl/dotnet/rapid/nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.org --no-symbols true
